export const endpoints = {
    auth: {
        login: "/login",
        signup: "/signup",
        me: "/me",
        ssoEnabled: "/sso/enabled",
        ssoLoginUrl: "/sso/login-url",
        ssoExchange: "/sso/exchange",
        changePassword: "/auth/change-password",
    },
    workspaces: "/workspaces",
    members: (workspaceId: string) => `/workspaces/${workspaceId}/members`,
    workspaceAccessReport: (workspaceId: string) => `/workspaces/${workspaceId}/access-report`,
    admin: {
        accounts: "/admin/accounts",
        workspaces: "/admin/workspaces",
        memberships: "/admin/memberships",
        systemConfig: "/admin/system-config",
        systemConfigTestEmail: "/admin/system-config/test-email",
        categories: "/admin/categories",
        features: "/admin/features",
        documents: "/content/documents",
        roles: "/admin/roles",
        permissions: "/admin/permissions",
        rolePermissions: "/admin/role-permissions",
        getRoleFeatures: (roleId: number) => `/admin/roles/${roleId}/features`,
        updateRoleFeatures: (roleId: number) => `/admin/roles/${roleId}/features`,
        getAvailableFeatures: "/admin/features/available",
        tasks: "/workflow/tasks",
        tasksParentOptions: "/workflow/tasks/parent-options",
        tasksAssignments: "/workflow/tasks/assignments",
        tasksAssigned: "/workflow/tasks/assigned",
        tasksReviews: "/workflow/tasks/reviews",
        tasksReminder: "/workflow/tasks/reminders",
        organizations: "/admin/organizations",
        files: "/content/files",
        fileSummary: (fileId: string) => `/content/files/${fileId}/summary`,
        fileDownload: (fileId: string, expiresIn = 300) => `/content/files/${fileId}/download?expiresIn=${expiresIn}`,
        filePreview: (fileId: string, expiresIn = 300) => `/content/files/${fileId}/preview?expiresIn=${expiresIn}`,
        notifications: "/content/notifications",
        notificationMarkRead: "/admin/notifications/mark-read",
        categoryItems: "/admin/category-items",
        taskComments: "/workflow/task-comments",
        taskProgress: "/workflow/task-progress",
        taskAssignmentProgress: "/workflow/task-assignment-progress",
        taskAssignments: "/workflow/task-assignments",
        auditLogs: "/admin/audit-logs",
        auditLogStats: "/admin/audit-logs/stats",
    },
    report: {
        reportTaskByDocument: "/report/reportTaskByDocument",
        reportTaskByOrganization: "/report/reportTaskByOrganization",
        reportTaskByField: "/report/reportTaskByField",
        reportTaskByDocumentType: "/report/reportTaskByDocumentType",
        reportTaskDetail: "/report/reportTaskDetail",
        reportTaskDetailExportExcel: "/report/reportTaskDetailExportExcel",
        reportTaskDetailExportPdf: "/report/reportTaskDetailExportPdf",
        reportTaskDashboard: "/report/reportTaskDashboard",
        reportTaskDashboardMainWorkload: "/report/reportTaskDashboardMainWorkload",
        reportTaskDashboardCoordinationWorkload: "/report/reportTaskDashboardCoordinationWorkload",
        reportTaskDashboardTotal: "/report/reportTaskDashboardTotal",
        reportTimelineDashboardTotal: "/report/reportTimelineDashboardTotal",
    },
    poverty: {
        households: "/poverty/households",
        householdsFromMap: "/poverty/households/from-map",
        household: (id: string | number) => `/poverty/households/${id}`,
        householdMembers: (id: string | number) => `/poverty/households/${id}/members`,
        householdMember: (id: string | number, memberId: string | number) => `/poverty/households/${id}/members/${memberId}`,
        householdAssessments: (id: string | number) => `/poverty/households/${id}/assessments`,
        householdAssessment: (id: string | number, assessmentId: string | number) => `/poverty/households/${id}/assessments/${assessmentId}`,
        householdContextHistories: (id: string | number) => `/poverty/households/${id}/context-histories`,
        householdContextHistory: (id: string | number, contextHistoryId: string | number) => `/poverty/households/${id}/context-histories/${contextHistoryId}`,
        householdSupports: (id: string | number) => `/poverty/households/${id}/supports`,
        householdSupport: (id: string | number, supportId: string | number) => `/poverty/households/${id}/supports/${supportId}`,
        householdChangeLogs: (id: string | number) => `/poverty/households/${id}/change-logs`,
        importExcel: "/poverty/households/import-excel",
        exportExcel: "/poverty/households/export-excel",
        gisMarkers: "/poverty/gis/markers",
        gisMarkerPosition: (id: string | number) => `/poverty/gis/markers/${id}/position`,
        dashboard: "/poverty/dashboard",
        reportSummary: "/poverty/reports/summary",
        reportExportExcel: "/poverty/reports/export-excel",
        reportDetail: "/poverty/reports/detail",
        reportDetailExportExcel: "/poverty/reports/detail/export-excel",
        locationProvinces: "/poverty/locations/provinces",
        locationWards: (provinceCode: string | number) => `/poverty/locations/wards?provinceCode=${provinceCode}`,
        locationAreas: (wardCode: string | number) => `/poverty/locations/areas?wardCode=${wardCode}`,
        wardPublicLinks: "/poverty/ward-public-links",
        publicWardBySlug: (slug: string) => `/public/poverty/wards/${slug}`,
        publicAreaBySlug: (slug: string, areaSlug: string) => `/public/poverty/wards/${slug}/areas/${areaSlug}`,
        publicHouseholdBySlug: (slug: string, householdId: string) => `/public/poverty/wards/${slug}/households/${householdId}`,
        wardOverviewsBase: "/poverty/ward-overviews",
        wardOverviews: (provinceCode: string | number, wardCode: string | number) =>
            `/poverty/ward-overviews?provinceCode=${provinceCode}&wardCode=${wardCode}`,
        wardOverviewById: (id: string | number) => `/poverty/ward-overviews/${id}`,
        wardAreas: (wardCode: string | number) => `/poverty/wards/${wardCode}/areas`,
        wardArea: (wardCode: string | number, areaId: string | number) => `/poverty/wards/${wardCode}/areas/${areaId}`,
    },
    imports: {
        template: (module: string) => `/admin/imports/${module}/template`,
        preview: (module: string) => `/admin/imports/${module}/preview`,
        commit: (module: string) => `/admin/imports/${module}/commit`,
    }
} as const;
